#!/bin/bash
# CodeMaker LaunchAgent wrapper — auto-generated by setup_autostart_macos.sh
# Uses the venv Python to run CodeMaker with proper environment.
export PATH="/Users/kartikeychaudhary/Desktop/CodeMaker/.venv/bin:$PATH"
cd "/Users/kartikeychaudhary/Desktop/CodeMaker"
exec "/Users/kartikeychaudhary/Desktop/CodeMaker/.venv/bin/python" -m codemaker
