#!/bin/bash

# ══════════════════════════════════════════════════════════════════
# CodeMaker — macOS Autostart Setup (launchd LaunchAgent)
# Creates a LaunchAgent plist to start CodeMaker on login.
#
# macOS sandbox restrictions:
#   - ~/Desktop, ~/Documents, ~/Downloads are protected locations.
#     launchd processes need Full Disk Access to read from them.
#   - We work around this by copying the launcher to
#     ~/Library/Application Support/CodeMaker/ (not protected).
#   - Logs go to ~/Library/Logs/CodeMaker/ (not protected).
# ══════════════════════════════════════════════════════════════════

set -e

# Ensure not running as root (LaunchAgents are per-user)
if [ "$EUID" -eq 0 ]; then
  echo "Do NOT run this script with sudo."
  echo "LaunchAgents run in user context. Run as: ./setup_autostart_macos.sh"
  exit 1
fi

PROJECT_DIR="$(cd "$(dirname "$0")" && pwd)"
VENV_PYTHON="$PROJECT_DIR/.venv/bin/python"
PLIST_NAME="com.codemaker.agent"
PLIST_DIR="$HOME/Library/LaunchAgents"
PLIST_PATH="$PLIST_DIR/$PLIST_NAME.plist"
LOG_DIR="$HOME/Library/Logs/CodeMaker"
LOG_PATH="$LOG_DIR/codemaker.log"

# Support dir is outside sandbox-protected areas
SUPPORT_DIR="$HOME/Library/Application Support/CodeMaker"
LAUNCHER_PATH="$SUPPORT_DIR/launcher.sh"

if [ ! -f "$VENV_PYTHON" ]; then
    echo "Error: Python virtual environment not found at $VENV_PYTHON"
    echo "Please set up the virtual environment first:"
    echo "  python3 -m venv .venv && source .venv/bin/activate && pip install -r requirements.txt"
    exit 1
fi

# Create directories
mkdir -p "$PLIST_DIR"
mkdir -p "$LOG_DIR"
mkdir -p "$SUPPORT_DIR"

# Unload existing agent if present
if launchctl list | grep -q "$PLIST_NAME" 2>/dev/null; then
    echo "Unloading existing CodeMaker agent..."
    launchctl unload "$PLIST_PATH" 2>/dev/null || true
fi

# ── Create launcher script in non-protected location ──
# ~/Library/Application Support/ is NOT sandbox-protected,
# unlike ~/Desktop which requires Full Disk Access.
echo "Creating launcher at $LAUNCHER_PATH..."

cat > "$LAUNCHER_PATH" << LAUNCHER_EOF
#!/bin/bash
# CodeMaker LaunchAgent launcher — auto-generated by setup_autostart_macos.sh
# Located in ~/Library/Application Support/ to avoid macOS sandbox restrictions.
export PATH="$PROJECT_DIR/.venv/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin"
export HOME="$HOME"
cd "$PROJECT_DIR" 2>/dev/null || cd "$HOME"
exec "$VENV_PYTHON" -m codemaker
LAUNCHER_EOF

chmod +x "$LAUNCHER_PATH"

# ── Create the plist ──
echo "Creating LaunchAgent at $PLIST_PATH..."

cat > "$PLIST_PATH" << EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>$PLIST_NAME</string>
    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>$LAUNCHER_PATH</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <dict>
        <key>SuccessfulExit</key>
        <false/>
    </dict>
    <key>StandardOutPath</key>
    <string>$LOG_PATH</string>
    <key>StandardErrorPath</key>
    <string>$LOG_PATH</string>
    <key>EnvironmentVariables</key>
    <dict>
        <key>PATH</key>
        <string>$PROJECT_DIR/.venv/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin</string>
        <key>HOME</key>
        <string>$HOME</string>
    </dict>
    <key>ThrottleInterval</key>
    <integer>30</integer>
</dict>
</plist>
EOF

echo "Loading CodeMaker agent..."
launchctl load "$PLIST_PATH"

# Wait a moment and check status
sleep 2
STATUS=$(launchctl list | grep "$PLIST_NAME" 2>/dev/null || echo "NOT FOUND")

echo ""
echo "✅ Autostart setup complete!"
echo "Agent status: $STATUS"
echo ""
echo "Log file:        $LOG_PATH"
echo "Launcher:        $LAUNCHER_PATH"
echo "To view logs:    tail -f $LOG_PATH"
echo "To stop:         launchctl unload $PLIST_PATH"
echo "To start:        launchctl load $PLIST_PATH"
echo "To remove:       launchctl unload $PLIST_PATH && rm $PLIST_PATH"
echo ""
echo "⚠️  Required permissions (System Settings → Privacy & Security):"
echo "   ✓ Accessibility        — for keyboard interception"
echo "   ✓ Screen Recording     — for screenshots"
echo "   ✓ Full Disk Access     — for bash to access ~/Desktop/CodeMaker"
echo "     (Add /bin/bash: press Cmd+Shift+G, type /bin/bash)"
echo ""
echo "💡 If it still doesn't work, check logs: tail -f $LOG_PATH"
